version: 2.1
description: A test orb with an example description.

jobs:
  greet:
    executor: ruby
    parameters:
      username:
        type: string
        description: A name of the user to greet
      emoji:
        type: enum
        enum: ['sushi']
        description: emoji name
        default: sushi      
      time:
        type: string
        description: number of display
        default: '1'

    steps:
      - run:
          name: Call Bye
          command: echo 'success to display'
      - run:
          command: emoji=`echo << parameters.emoji >> | tr '[:lower:]' '[:upper:]'`;  eval "echo \$$(echo $emoji)"


commands:

  hello:
    description: Greet the user politely
    parameters:
      username:
        type: string
        description: A name of the user to greet
    steps:
      - run: "echo 'CircleCI Orbs ミニハッカソンへようこそ、<< parameters.username >>！'"

  # bye:
  #   description: Good bye :)
  #   parameters:
  #     username:
  #       type: string
  #       description: A name of the user to greet
  #   steps:
  #     - run: "echo -e \"<< parameters.emoji >> ${LIGHT_GREEN}<< parameters.username >>${NC}！\""

executors:
  ruby:
    docker:
      - image: circleci/ruby:latest
    environment:
      LIGHT_GREEN: '\033[40m\033[1;32m'
      NC: '\033[0m'
      SUSHI: "\\U0001F363"
      BEER: "\\U0001F37A"



