version: 2.1
description: display emojis some times

jobs:
  echo:
    executor: ruby
    parameters:
      emoji:
        type: enum
        enum: ['sushi', 'beer']
        description: emoji name
        default: sushi      
      time:
        type: integer
        description: number of display
        default: 10

    steps:
      - run:
          name: echo
          command: emoji=`echo << parameters.emoji >> | tr '[:lower:]' '[:upper:]'`;  for i in {1..<< parameters.time >>}; do eval "echo -ne \$$(echo $emoji)"; done

executors:
  ruby:
    docker:
      - image: circleci/ruby:latest
    environment:
      LIGHT_GREEN: '\033[40m\033[1;32m'
      NC: '\033[0m'
      SUSHI: "\\U0001F363"
      BEER: "\\U0001F37A"



