version: 2.1
description: A test orb with an example description.

jobs:
  bye:
    executor: ruby
    parameters:
      username:
        type: string
        description: A name of the user to greet
    steps:
      - run:
          name: Call Bye
          command: echo 'success to display'
      - bye:
          username: << parameters.username >>

commands:
  hello:
    description: Greet the user politely
    parameters:
      username:
        type: string
        description: A name of the user to greet
    steps:
      - run: "echo 'CircleCI Orbs ミニハッカソンへようこそ、<< parameters.username >>！'"

  bye:
    description: Good bye :)
    parameters:
      username:
        type: string
        description: A name of the user to greet
    steps:
      - run: "echo -e '🍺🍣 ${LIGHT_GREEN}<< parameters.username >>${NC}！'"

executors:
  ruby:
    docker:
      - image: circleci/ruby:latest
    environment:
      LIGHT_GREEN: '\033[40m\033[1;32m'
      NC: '\033[0m'
