version: 2.1

orbs:
  awesome-emoji: a4geru/awesome-emoji@dev:first

workflows:
  main:
    jobs:
      - awesome-emoji/echo:
          username: 4geru
          emoji: beer
          time: 10

# neko