version: 2.1

orbs:
  awesome-emoji: a4geru/awesome-emoji@volatile

jobs:
  build:
    docker:
    - image: bash
    steps:
      - run: "echo 'testing building...'"
      - awesome-emoji/echo:
          emoji: beer

workflows:
  main:
    jobs:
      - build

